<script lang="ts">
  import { onMount } from 'svelte';

  // D-ummy data representing recipes generated by AI
  let recipes = [
    {
      id: '1',
      meal_name: 'Quick Lemon Herb Chicken',
      time_to_prepare: 20,
      image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 
    },
    {
      id: '2',
      meal_name: 'Spicy Shrimp Stir-fry',
      time_to_prepare: 15,
      image: 'https://images.unsplash.com/photo-1599557422934-0d7f9b8c06e2?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
    {
      id: '3',
      meal_name: 'Vegetable Curry',
      time_to_prepare: 30,
      image: 'https://images.unsplash.com/photo-1596422849221-3b7428f69c29?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
    {
      id: '4',
      meal_name: 'Classic Beef Tacos',
      time_to_prepare: 25,
      image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=2881&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
  ];

  onMount(() => {
    // In a real application, you would fetch the recipes from an API here
    // For example:
    // async function fetchRecipes() {
    //   const response = await fetch('/api/recipes');
    //   recipes = await response.json();
    // }
    // fetchRecipes();
  });
</script>

<svelte:head>
  <title>AI-Generated Recipes</title>
  <meta name="description" content="A collection of recipes generated by AI." />
</svelte:head>

<div class="container">
  <h1>Your AI-Generated Recipes</h1>
  <p>Here are some meal ideas generated just for you. Click on a card to see the full recipe.</p>

  <div class="recipe-grid">
    {#each recipes as recipe (recipe.id)}
      <a href={`/recipe/${recipe.id}`} class="recipe-card">
        <img src={recipe.image} alt={`A photo of ${recipe.meal_name}`} />
        <div class="card-content">
          <h2>{recipe.meal_name}</h2>
          <p>{recipe.time_to_prepare} minutes to prepare</p>
        </div>
      </a>
    {/each}
  </div>
</div>

<style>
  .container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  }

  h1 {
    text-align: center;
    margin-bottom: 1rem;
    color: #333;
  }

  p {
    text-align: center;
    margin-bottom: 3rem;
    color: #666;
  }

  .recipe-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 2rem;
  }

  .recipe-card {
    background: #fff;
    border-radius: 12px;
    box-shadow: 0 8px 16px rgba(0,0,0,0.1);
    overflow: hidden;
    text-decoration: none;
    color: inherit;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
  }

  .recipe-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 12px 24px rgba(0,0,0,0.15);
  }

  .recipe-card img {
    width: 100%;
    height: 200px;
    object-fit: cover;
  }

  .card-content {
    padding: 1.5rem;
  }

  .card-content h2 {
    margin-top: 0;
    margin-bottom: 0.5rem;
    font-size: 1.5rem;
    color: #333;
  }

  .card-content p {
    margin: 0;
    color: #555;
    font-size: 1rem;
    text-align: left;
  }
</style>
